language: cpp
os: osx
osx_image:
  - xcode10.1
  - xcode11.2
env:
  global:
  - MAKEFLAGS="-j2"
  - Qt5Core_DIR=/usr/local/opt/qt/lib/cmake/Qt5Core
  - Qt5Gui_DIR=/usr/local/opt/qt/lib/cmake/Qt5Gui
  - Qt5Test_DIR=/usr/local/opt/qt/lib/cmake/Qt5Test
  - Qt5Widgets_DIR=/usr/local/opt/qt/lib/cmake/Qt5Widgets
  - Qt5Xml_DIR=/usr/local/opt/qt/lib/cmake/Qt5Xml

before_install:
  - brew update
  - brew uninstall -f poppler gdal postgis python@2 mercurial
  - brew install poppler --only-dependencies
  - brew upgrade cmake pkg-config && brew install ninja
  - mkdir build && cd build
script: cmake .. -G Ninja -DFONT_CONFIGURATION=generic -DBUILD_SHARED_LIBS=OFF && ninja