language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

matrix:
  include:
    - dist: trusty
      compiler: clang
      before_install:
        - sudo add-apt-repository ppa:ricotz/testing -y
        - sudo add-apt-repository ppa:aacid/openjp2trusty -y
        - sudo apt-get -qq update
        - sudo apt-get install -y libopenjp2-7-dev qtbase5-dev gobject-introspection libglib2.0-dev libgtk-3-dev libgirepository1.0-dev libnss3-dev ninja-build
      script: cmake . -G Ninja -DFONT_CONFIGURATION=generic && ninja

    - os: osx
      osx_image: xcode10.1
      before_install:
        - brew uninstall poppler gdal postgis python@2 mercurial
        - brew install poppler --only-dependencies --build-from-source
      script: cmake . -DFONT_CONFIGURATION=generic -DBUILD_SHARED_LIBS=OFF && make

    - os: osx
      osx_image: xcode11.2
      before_install:
        - brew uninstall poppler gdal postgis
        - brew install poppler --only-dependencies --build-from-source
      script: cmake . -DFONT_CONFIGURATION=generic -DBUILD_SHARED_LIBS=OFF && make

