name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]

    steps:
    - uses: actions/checkout@v4

    # need to rm -rf Mono because otherwise cmake finds that cmake
    # instead of the brew one and everything breaks
    - name: Install dependencies
      run: |
        brew list
        brew list --cask
        brew uninstall -f python@3.8 python@3.10 python@3.11 azure-cli pipx aws-sam-cli llvm cffi pycparser python-cryptography node@18 node mongodb-community@5.0 mongosh cmake
        brew update
        brew install ninja boost cmake glib qt6 gpgme
        brew install poppler --only-dependencies
        sudo rm -rf /Library/Frameworks/Mono.framework
        sudo rm -rf /Library/Receipts/MonoFramework-*
    
    - name: Clone test files
      working-directory: ${{github.workspace}}
      run: git clone git://git.freedesktop.org/git/poppler/test testfiles

    - name: Configure CMake
      run: |
        if [[ "${{ matrix.os }}" == "macos-14" ]]; then
          sudo xcode-select -s /Applications/Xcode_16.2.app
        fi
        cmake -DENABLE_QT5=OFF -DCMAKE_CXX_FLAGS="-Werror -Wno-deprecated-declarations" -B ${{github.workspace}}/build -G Ninja -DFONT_CONFIGURATION=generic -DBUILD_SHARED_LIBS=OFF -DTESTDATADIR=${{github.workspace}}/testfiles


    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
      
